---
name: publish wheels to testpypi

on: push
  # TODO(retr0h): will enable prior to merge, testing action
  # push:
  #   branches:
  #     - main
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/python-gilt

    permissions:
      # mandatory for trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Wheels
        run: task build:wheel
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
